apiVersion: apps/v1
kind: Deployment

metadata:
  name: {{ include "task-2-49-chart.fullname" . }}

spec:
  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      app: {{ include "task-2-49-chart.fullname" . }}

  template:
    metadata:
      labels:
        app: {{ include "task-2-49-chart.fullname" . }}

    spec:
      containers:
        - name: nginx

          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"

          imagePullPolicy: {{ .Values.image.pullPolicy }}

          ports:
            - containerPort: {{ .Values.containerPort }}

          envFrom:
            - configMapRef:
                name: {{ include "task-2-49-chart.fullname" . }}