apiVersion: v1
kind: Service

metadata:
  name: {{ include "task-2-49-chart.fullname" . }}

spec:
  type: {{ .Values.service.type }}

  selector:
    app: {{ include "task-2-49-chart.fullname" . }}

  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.containerPort }}