grafana:
  adminPassword: admin123

  additionalDataSources:
    - name: Loki
      uid: loki
      type: loki
      access: proxy
      url: http://akash-loki-stack:3100

    - name: Prometheus
      uid: prometheus
      type: prometheus
      access: proxy
      url: http://akash-prometheus-stack-kub-prometheus:9090
      isDefault: true

  ingress:
    enabled: true
    ingressClassName: nginx

    hosts:
      - grafana.codexakash.space

    tls:
      - secretName: grafana-tls
        hosts:
          - grafana.codexakash.space

  persistence:
    enabled: true
    size: 5Gi

# Existing cluster CRDs already exist
crds:
  enabled: false

# Reuse cluster-wide operator
prometheusOperator:
  enabled: false

alertmanager:
  enabled: true

  ingress:
    enabled: true
    ingressClassName: nginx

    hosts:
      - alertmanager.codexakash.space

    tls:
      - secretName: alertmanager-tls
        hosts:
          - alertmanager.codexakash.space

  alertmanagerSpec:
    storage:
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 2Gi

prometheus:
  ingress:
    enabled: true
    ingressClassName: nginx

    hosts:
      - prometheus.codexakash.space

    tls:
      - secretName: prometheus-tls
        hosts:
          - prometheus.codexakash.space

  prometheusSpec:
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 10Gi

nodeExporter:
  enabled: false

prometheus-node-exporter:
  enabled: false