repositories:
  - name: ingress-nginx
    url: https://kubernetes.github.io/ingress-nginx

  - name: jetstack
    url: https://charts.jetstack.io

  - name: prometheus-community
    url: https://prometheus-community.github.io/helm-charts

  - name: grafana
    url: https://grafana.github.io/helm-charts

helmDefaults:
  atomic: true
  wait: true

releases:

  - name: ingress-nginx
    namespace: ingress-nginx
    createNamespace: true
    kubeContext: akash-c-a@kubenine
    chart: ingress-nginx/ingress-nginx
    version: 4.15.1
    values:
      - values/ingress-nginx.yaml

  - name: cert-manager
    namespace: cert-manager
    createNamespace: true
    kubeContext: akash-c-a@kubenine
    chart: jetstack/cert-manager
    version: v1.18.2
    values:
      - values/cert-manager.yaml

  - name: akash-prometheus-stack
    namespace: akash-c-a-monitoring
    createNamespace: true
    kubeContext: akash-c-a@kubenine
    chart: prometheus-community/kube-prometheus-stack
    version: 75.6.2
    values:
      - values/akash-prometheus-stack.yaml

  - name: akash-loki-stack
    namespace: akash-c-a-monitoring
    createNamespace: true
    kubeContext: akash-c-a@kubenine
    chart: grafana/loki-stack
    version: 2.10.2
    values:
      - values/akash-loki-stack.yaml